name: Create Ubuntu and Windows Releases

on:
  push:
    tags:
    - '*'

  workflow_dispatch:

jobs:
  build-linux:

    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - run: docker pull ghcr.io/xlightssequencer/xlights-build-docker:master
      - run: docker run --name buildvm ghcr.io/xlightssequencer/xlights-build-docker:master /bin/bash Recipe.xSchedule.appimage
      - run: 'docker cp buildvm:/xSchedule/xSchedule/AppImage/ /tmp/'
      - run: ls -lh /tmp/AppImage

      - uses: ncipollo/release-action@v1
        with:
           allowUpdates: true
           artifacts: "/tmp/AppImage/*.AppImage"
           token: ${{ secrets.GITHUB_TOKEN }}

  build-windows:
   runs-on: windows-2025-vs2026

   steps:
    - name: Checkout xSchedule
      uses: actions/checkout@v4
      with:
          submodules: 'recursive'

    - name: Build xSchedule
      shell: cmd
      working-directory: build_scripts\msw
      run: call build_xSchedule_x64.cmd < NUL

    - name: Build Installer
      working-directory: build_scripts\msw
      run: ISCC.exe xSchedule_64bit.iss

    - uses: ncipollo/release-action@v1
      with:
           allowUpdates: true
           artifacts: 'build_scripts\msw\output\*'
           token: ${{ secrets.GITHUB_TOKEN }}
