name: Windows xSchedule CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-2025-vs2026
    steps:
    - name: Checkout xSchedule
      uses: actions/checkout@v4
      with:
          submodules: 'recursive'
    - name: Build xSchedule
      shell: cmd
      run: call build_scripts\msw\build_xSchedule_x64.cmd < NUL

    - name: Unit tests
      shell: cmd
      run: call xSchedule\tests\build_tests_msw.cmd < NUL

    - name: Upload xSchedule Exe
      uses: actions/upload-artifact@v4
      with:
        name: xSchedule_Exe
        path: 'xSchedule\x64\Release\xSchedule.exe'
